### ISSUE TITLE
Use this via npm

### ISSUE THREAD

**Issue by netgfx** [Shinao/PathToPoints#1]
Hello,

I was wondering if I can use this via npm?

**Comment by Shinao** [comment]
Hi there,

There is no npm package for PathToPoints, it might be possible to use it without the browser but I'm not sure since there is a couple of dependencies (like Raphael.js) that I used which may or may not be browser use only. 
I don't have time to try to create a standalone version but if you find the time and are willing to do it I will update the repo accordingly.

Cheers
